import re
import json
from requests.exceptions import RequestException
from logging import error, info
from typing import Tuple, Optional

from config import TOKEN_FILE
from utils import Warp
from handlers.portal_handler import PortalHandler
from handlers.secret_handler import get_secret_handler


class SessionHandler:

    @staticmethod
    def parse_session_details(html: str) -> Tuple[str, str]:
        # Response html contains a url with a keepalive token
        match = re.search(r'http://([^/]+)/keepalive\?([^"]+)', html)
        assert match is not None
        ip = match.group(1)
        token = match.group(2)
        info(f"Session - ip: {ip} token: {token}")

        with open(TOKEN_FILE, "w") as f:
            json.dump(
                {
                    "_comment": "This file is auto-generated by IIITK Portal Loginator",
                    "ip": ip,
                    "token": token,
                },
                f,
            )
        info("Session details saved.")

        return ip, token

    @staticmethod
    def get_session_details() -> Tuple[str, str]:
        """
        Raises:
            ValueError: If no session token is found.
        """
        try:
            with open(TOKEN_FILE, "r") as f:
                data = json.load(f)
                return data["ip"], data["token"]
        except:
            error("No session token found. Please login first.")
            raise ValueError("No session token found. Please login first.")

    @staticmethod
    def login(
        *, username: Optional[str] = None, password: Optional[str] = None
    ) -> None:
        try:
            if username is None:
                username, password = get_secret_handler().get_first_matching_credentials()
            elif password is None:
                username, password = get_secret_handler().get_user_credentials(username)
        except ValueError as e:
            error(e)
            return

        try:
            Warp.disconnect()
            login_response = PortalHandler.login_to_portal(username, password)
            if login_response is None:
                return None

            SessionHandler.parse_session_details(login_response)
        except (RequestException, ValueError):
            pass
        finally:
            Warp.restore()
